### PR TITLE
Add Jotai to peer dependencies

### PR DESCRIPTION
**Pull request by byarmis**
[This commit](https://github.com/daily-co/daily-react/commit/550f45bc30fb144e5d842ce7da7ac194c24a7328#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) dealt with removing Recoil and replacing it with Jotai.  Recoil was removed as a peer dependency but Jotai was not added.

This PR serves to add Jotai as a peer dependency.

If you me to open an issue that this PR resolves, I can do that as well.

### CODE REVIEW

**Comment by jamsea** [comment]
Looks good to me, thanks @byarmis! I'm not an admin so I can't click the approve button but @Regaddi can double check

**Comment by Regaddi** [comment]
This has been included in [0.21.1](https://github.com/daily-co/daily-react/releases/tag/daily-react-2024-10-08-0.21.1).

**Comment by stevebrowndotco** [comment]
Hi, apologies if I am mistaken, but FYI I have updated 0.21.1 but I am still required to install jotai on my project, even though I have no direct dependencies on jotai. It is because of this package.

**Comment by Regaddi** [comment]
Hey @stevebrowndotco,

in 0.21.0 jotai was only defined as a dev dependency, which aren't installed through a regular `npm i @daily-co/daily-react`.
0.21.1 added jotai as a peer dependency. With `npm>=7` this should be installed automatically when running `npm i @daily-co/daily-js @daily-co/daily-react`. You don't have to add jotai specifically to your project, if you don't use it in your app.

It's a little different with `yarn`, because yarn does not auto-resolve peer dependencies.

Hope this clarifies the intent of this PR ☺️

**Comment by stevebrowndotco** [comment]
Hi @Regaddi thank you for your reply. With npm 10 I am still getting the error:

`ERROR in ./node_modules/@daily-co/daily-react/dist/daily-react.esm.js 3:0-62
Module not found: Error: Can't resolve 'jotai' in 'redacted/node_modules/@daily-co/daily-react/dist'` I have tried the usual suspects such as emptying my node_modules, running npm install etc. The package definitely resolves to 0.21.1 . Should I raise an issue I wonder?

**Comment by jamsea** [comment]
Hi @stevebrowndotco, you need to install `jotai` as it's a peer dependency for this project.  

```
npm i @daily-co/daily-js @daily-co/daily-react jotai
```

Should do it. Sometimes people have an npmrc setting that automatically install peer dependencies and sometimes they don't so that could be why it didn't automatically install.

**Comment by stevebrowndotco** [comment]
Ack, I misunderstood the intention. I was expecting not to have to install jotai, but it is infact the opposite. Thank you for the great library and apologies for the hassle.

**Pull request closed without merging**
